version: "3.9"
   
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        depends_on:
            db:
                condition: service_healthy

        links:
            - db:db
        networks:
            - djangonetwork


    db:
        image: postgres
        container_name: db
        environment:
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
        # volumes:
            # - ./data/db:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

        networks:
            - djangonetwork

networks:
    djangonetwork:
        driver: bridge