# Generated by Django 3.2.11 on 2022-04-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis_code', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosiscode',
            old_name='diagnosis_code',
            new_name='code',
        ),
    ]
